---
name: DBD-PO
version: 0.07
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
abstract: 'DBD::PO - DBI driver for PO files'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 0
  Params::Validate: 0
  SQL::Statement: 0
  parent: 0
build_requires:
  Encode: 0
  Test::Simple: 0
recommends:
  DBD::File: 0
  SQL::Parser: 0
  Test::Differences: 0
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  DBD::PO:
    file: lib/DBD/PO.pm
    version: 0.07
  DBD::PO::Locale::PO:
    file: lib/DBD/PO/Locale/PO.pm
    version: 0.21.01
  DBD::PO::Statement:
    file: lib/DBD/PO/Statement.pm
  DBD::PO::Table:
    file: lib/DBD/PO/Table.pm
  DBD::PO::Text::PO:
    file: lib/DBD/PO/Text/PO.pm
  DBD::PO::db:
    file: lib/DBD/PO/db.pm
  DBD::PO::dr:
    file: lib/DBD/PO/dr.pm
  DBD::PO::st:
    file: lib/DBD/PO/st.pm
  Test::DBD::PO::Defaults:
    file: lib/Test/DBD/PO/Defaults.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
